version: '3.8'

services:
  db:
    restart: always
    image: postgres:14.1-alpine
    volumes:
      - ./.database:/var/lib/postgressql/data
    ports:
      - 5432:5432
    networks:
      - dryve
    environment:
      POSTGRES_USER: 'server'
      POSTGRES_PASSWORD: 'verystrongpassword'
      POSTGRES_DB: 'main'

  server:
    build: .
    depends_on:
      - db
    restart: always
    volumes:
      - ./.data:/tmp/dryve-filestorage
      - ${PWD}/config-docker.json:/config.json
    ports:
      - 8666:8666
    networks:
      - dryve
    environment:
      TEST: 'test'

networks:
  dryve:
    driver: bridge