version: '3.8'

services:
  db:
    restart: always
    image: postgres:14.1-alpine
    volumes:
      - ./.database/postgres/data:/var/lib/postgressql/data
    ports:
      - 5432:5432
    networks:
      - dryve
    environment:
      POSTGRES_USER: 'server'
      POSTGRES_PASSWORD: 'verystrongpassword'
      POSTGRES_DB: 'main'
networks:
  dryve:
    driver: bridge